Actions: Reduce scipy pinned version number to 1.11.4
```
LibMambaUnsatisfiableError: Encountered problems while solving:
  - package scipy-1.12.0-py310hdfaad59_0 requires python >=3.10,<3.11.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ pin-1 is installable and it requires
│  └─ python 3.8.* , which can be installed;
└─ scipy 1.12.0  is not installable because there are no viable options
   ├─ scipy 1.12.0 would require
   │  └─ python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;
   ├─ scipy 1.12.0 would require
   │  └─ python >=3.11,<3.12.0a0 , which conflicts with any installable versions previously reported;
   ├─ scipy 1.12.0 would require
   │  └─ python >=3.12,<3.13.0a0 , which conflicts with any installable versions previously reported;
   └─ scipy 1.12.0 would require
      └─ python >=3.9,<3.10.0a0 , which conflicts with any installable versions previously reported.
```