Workflow: Troubleshoot Windows MATLAB not loading python
 Error: Caught "std::exception" Exception message is:
  Unable to launch Simple server: Unable to launch C:\Program Files\MATLAB\R2023b\interprocess\bin\win64\pycli\MATLABPyHost.exe
  because: Peer process exited before transport type handshake. Exit status: 3221226505

  ERROR: MATLAB error Exit Status: 0x00000001
  exit status 1

Maybe need MATLAB Engine API for python https://www.mathworks.com/help/matlab/matlab_external/install-the-matlab-engine-for-python.html ?

MacOS: Brew install hdf5 and netcdf

Ubuntu: Set MATLAB pyenv Execution Mode to OutOfProcess

Windows: pip failing to install matlab engine, trying only binary flag...

# 51

Windows only: Install matlab engine per: https://pypi.org/project/matlabengine/

Ubuntu tests ran to completion!
Macos Still failing at pip install mhkit, specifically the hd5py wheel build step. Pip installing numpy

53

54

Actually pip install numpy on macos, only test mhkit python on windows

55

Macos - no change, Following https://stackoverflow.com/questions/66741778/how-to-install-h5py-needed-for-keras-on-macos-with-m1 and exporting HDF5_DIR

56

Macos: Skip brew install entirely
Windows: Skip install of matlab engine
All: Use OutOfProcess for matlab python

57

Macos: use only-binary flag

58: Uninstall mhkit prior to installing mkhit

59: Explicitly setup python on ubuntu and macos. Seems like macos is using python2. Also explicitly use python3 and pip3

60: Printing mhkit version fails. Only try to import mhkit.

61:  MacOS Install mhkit from pip not source

62: Attempt to verify mhkit install

63: try to install from source with pip not pip3

64: Remove only binary flag on pip source install

65: Remove python3/pip3

66: Simplify mhkit version call

67: Macos is working, now ubuntu is not. Outputting pip freeze

68: Install mhkit from pip cloud, not local

69: Use latest versions of actions/checkout@v4 and actions/setup-python@v4

Should fix errors with older github actions that show up at the bottom of the workflow run output

70: Only test on windows, see if this helps with License Manager issues

71: Test MHKIT python import first in MATLAB

72: Correct 71

73: Try not changing execution mode to out of process

74: See if we can import h5py

75: Add output python path to run.m. Matlab does this once per run, and we set in in the last run, so we are seeing matlab use the system python, but we want it to use the conda python version.

76: Output run.m, still seeing same problem as 75

78: Use pyenv to set python version

79: Explicitly set python version, not sure why the same command run through echo outputs a different result. Seeing run.m before using is smart.

80: Echo with newline

81: Now try ExecutionMode OutOfProcess...

82: Got this error again: Unable to launch Simple server: Unable to launch C:\Program Files\MATLAB\R2023b\interprocess\bin\win64\pycli\MATLABPyHost.exe

Going to try pip installing matlabengine again...

83: Use matlabengine pip install instructions on github...

84: Use powershell to pass anaconda version to run.m file...

85: Fix powershell cmd...

86: Actually fix powershell cmd

87: Use InProcess for Windows Matlab python, does not work for mhkit, but at least tests run...