Actions: Use numpy 1.24.4 on unix
Based on this error:

```
LibMambaUnsatisfiableError: Encountered problems while solving:
  - package numpy-1.26.4-py310h4bfa8fc_0 requires python >=3.10,<3.11.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ numpy 1.26.4  is installable with the potential options
│  ├─ numpy 1.26.4 would require
│  │  └─ python >=3.10,<3.11.0a0 , which can be installed;
│  ├─ numpy 1.26.4 would require
│  │  └─ python >=3.11,<3.12.0a0 , which can be installed;
│  ├─ numpy 1.26.4 would require
│  │  └─ python >=3.12,<3.13.0a0 , which can be installed;
│  └─ numpy 1.26.4 would require
│     └─ python >=3.9,<3.10.0a0 , which can be installed;
└─ pin-1 is not installable because it requires
   └─ python 3.8.* , which conflicts with any installable versions previously reported.

Pins seem to be involved in the conflict. Currently pinned specs:
 - python 3.8.* (labeled as 'pin-1')
```